test_that("Test HexCubeCenter", {
  x = c(1,2,-3)
  y = c(0,0,0)
  h1 = HexCubeCenter$new(x)
  expect_type(h1, "environment")
  expect_true(inherits(h1, "HexCubeCenter"))
  expect_type(h1$value, 'double')
  expect_length(h1$value, 3)
  expect_equal(h1$dim(), 3)
  expect_equal(dim(h1), 3)
  expect_type(h1$q, 'double')
  expect_length(h1$q, 1)
  expect_equal(h1$q, x[1])
  expect_type(h1$r, 'double')
  expect_length(h1$r, 1)
  expect_equal(h1$r, x[2])
  expect_type(h1$s, 'double')
  expect_length(h1$s, 1)
  expect_equal(h1$s, x[3])

  h1$set(y)
  expect_equal(h1$s, 0)
  expect_equal(h1$s, h1$q)
  expect_equal(h1$s, h1$r)

  h1 = HexCubeCenter$new(x)
  h2 = HexCubeCenter$new(y)
  expect_equal(add(h1, h2)$value, x)
  expect_equal(subtract(h2, h1)$value, -x)

  h1 = HexCubeCenter$new(x)
  d1 = hex_direction(1)
  expect_equal(add(h1, d1)$value, hex_neighbour(h1, 1)$value)
  h1 = HexCubeCenter$new(x)
  dd1 = hex_diagonal_direction(1)
  expect_equal(add(h1, dd1)$value, hex_diagonal_neighbour(h1, 1)$value)
})
