test_that("Test Hexagon", {
  x = c(0,0,0)
  y = c(2,2,-4)
  po = c(260464,6246874)
  sz = 200
  h1 = PointyHexagon$new(x, size=sz, planar_origin=po)
  expect_true(inherits(h1$center, "HexCubeCenter"))
  expect_true(inherits(h1$get_planar_center(), "Coords"))
  expect_equal(h1$center$value, x)
  expect_equal(h1$get_planar_center()$value, po)
  expect_equal(h1$get_planar_center()$value, h1$planar_origin)
  expect_type(h1$height, "double")
  expect_type(h1$is_pointy(), "logical")
  expect_equal(h1$height, sz*2)
  h2 = h1$set_center(y, in_place=FALSE)
  expect_equal(h2$center$value, y)
  h1 = PointyHexagon$new(x, size=sz, planar_origin=po)
  h2 = h1$shift_along_direction(1, 1, in_place=FALSE)
  h3 = h1$shift_along_q(1, in_place=FALSE)
  expect_equal(h1$center$value, x)
  expect_true(identical(h1$center$value, x))
  expect_false(identical(h2$center$value, x))
  expect_equal(h2$center$value, h3$center$value)
  h2 = h1$shift_along_direction(1, 6, in_place=FALSE)
  h3 = h1$shift_along_r(1, in_place=FALSE)
  expect_false(identical(h2$center$value, x))
  expect_equal(h2$center$value, h3$center$value)
  h1 = PointyHexagon$new(x, size=1, planar_origin=c(0,0))
  pol = h1$to_polygon()
  expect_type(pol, "list")
  expect_true(inherits(pol, "sfg"))
  expect_true(inherits(pol, "POLYGON"))
  expect_equal(x[1], st_coordinates(st_centroid(pol))[1], 0.01)
  expect_equal(x[2], st_coordinates(st_centroid(pol))[2], 0.01)
  expect_type(h1$v_planar_coordinates(), "double")
  expect_length(h1$v_planar_coordinates(), 12)
})


